### ISSUE TITLE
[BUG]TokenizerError  message: "Unterminated string literal"  when dump mysql

### ISSUE THREAD

**Issue by koolay** [Qovery/Replibyte#158] opened 2022-06-08 07:24 UTC
**Replibyte version is 0.8.6.**

```
⠲ [00:00:00] [>---------------------------------------------------------------------------------------------------] 3.93KiB/100.00MiB (1h)
failing query: '
CREATE TABLE `alert_source` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'id',
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '',
  `code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Code/loki label',
  `enabled` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '',
  `token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT ',
  `source_fields` json DEFAULT NULL COMMENT '',
  `company_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '公司ID',
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `created_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '',
  `modified_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `modified_by` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='';'
thread 'main' panicked at 'TokenizerError { message: "Unterminated string literal", line: 16, col: 19 }', dump-parser/src/mysql/mod.rs:708:13
stack backtrace:
```

**Comment by evoxmusic** [comment] 2022-06-12 06:40
Hi @koolay , can you give me the complete SQL query to reproduce the error on my end and provide a fix? Thx

**Comment by marcoacierno** [comment] 2022-06-12 15:31
I think I am getting the same error, just on postgres

```
thread 'main' panicked at 'TokenizerError { message: "Unterminated string literal", line: 469, col: 100 }', dump-parser/src/postgres/mod.rs:761:13
⠒ [00:00:12] [>-----------------------------------------------------------------------] 756.56KiB/100.00MiB (27m)
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: dump_parser::postgres::get_tokens_from_query_str
   3: replibyte::source::postgres::read_and_transform::{{closure}}
   4: dump_parser::utils::list_sql_queries_from_dump_reader
   5: <replibyte::source::postgres::Postgres as replibyte::source::Source>::read
   6: <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run
   7: replibyte::commands::dump::run
   8: replibyte::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is the last query it prints before throwing the error:

```
INSERT INTO public.grants_grant (id, created, modified, name, full_name, email, age, gender, occupation, grant_type, python_usage, been_to_other_events, interested_in_volunteering, needs_funds_for_travel, why, notes, travelling_from, conference_id) VALUES (12, '2020-02-14 23:15:56.759943+00', '2020-02-14 23:15:56.759943+00', 'xxxxxx', 'xx', 'xxxxx', 0, 'xxxx', 'xxxx', 'xxxxx', 'xxxxxxxxx', 'there is some text here and then a list:

'
```

I removed the text, but what followed was a long string with newlines

The selected text from postgres looks like this:

```
                                                aaalaaa
--------------------------------------------------------------------------------------------------------
 a aaaa a aaaa aaa aaaaaaaa aa aaa aaaaaaaaa aaaaaaa aaa:                                               +
                                                                                                        +
     aaaaaa aaaaaa 1990 - aaaaa, aaaaa (aaaa)                                                           +
     aaataaa aak aa aaaa 1990 - aaaaaaak, aaaaaaa (aaaksaaa) : aaakaaaza aaataaa / ajaaaa aaajaat       +
     aaaaaa UK 1990 - aaaaaaa, aalas (aaaa)                                                             +
     aaaaaa aaaaaaa 1990 - aaaaaaak, aaaaaaa ( aaaksaaa) : aata aaalaasas aaa Vasualazataaa aaa aaaaaaaa+
     aaaaaa aaaaaaa 1990- aaaaaaak, aaaaaaa (aaaa)                                                      +
     aaaautaa aaaa 1990 - aaaaaaak, aaaaaaa (aaaksaaa) : aaa aavalaaaaat aata ajaaaa                    +
     aaaautaa aaaa 1990 - aaaaaaak, aaaaaaa (aaaksaaa) : aaataaa aaajaat aata aasaaaaaaa aa
```

(replaced content )

**Comment by evoxmusic** [comment] 2022-06-18 06:35
@koolay @marcoacierno can you give me the complete query that make crashing replibyte? It will help to reproduce it and provide a fix 🙏🏽

**Comment by evoxmusic** [comment] 2022-06-18 06:39
@koolay this query is not complete:

```
INSERT INTO public.grants_grant (id, created, modified, name, full_name, email, age, gender, occupation, grant_type, python_usage, been_to_other_events, interested_in_volunteering, needs_funds_for_travel, why, notes, travelling_from, conference_id) VALUES (12, '2020-02-14 23:15:56.759943+00', '2020-02-14 23:15:56.759943+00', 'xxxxxx', 'xx', 'xxxxx', 0, 'xxxx', 'xxxx', 'xxxxx', 'xxxxxxxxx', 'there is some text here and then a list:

'
```

Can you give me the complete query (I think there are missing fields at the end). Thank you

**Comment by evoxmusic** [comment] 2022-06-25 20:25
I close this issue until you can give a query to reproduce this issue.

**Closed by evoxmusic** 2022-06-25 20:25 UTC
Labels: bug
