### ISSUE TITLE
panic: Unterminated string literal in SQL instruction

### ISSUE THREAD

**Issue by fazo96** [Qovery/Replibyte#94] opened 2022-05-10 10:56 UTC
Hello, at Flexhire we are trying out this tool to seed our staging DB with production data.

We are using replibyte v0.6 for Linux x86 and the dump is of a PostgreSQL 11 DB hosted on AWS RDS.

When generating a dump from our production DB we are encountering the following crash. I included a stack backtrace generated with `RUST_BACKTRACE=full`

We have `text` columns containing user entered text in the markdown format that might have characters such as `'`. The application uses rails so these characters should be escaped. Perhaps there is some issue with the escaping done by Replibyte? It looks like `INSERT` instructions are the ones causing the problem.

```
thread 'main' panicked at 'TokenizerError { message: "Unterminated string literal", line: 1, col: 788 }', dump-parser/src/postgres/mod.rs:747:13
stack backtrace:
   0:     0x7f147c81bc5d - std::backtrace_rs::backtrace::libunwind::trace::h081201764674ef17
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f147c81bc5d - std::backtrace_rs::backtrace::trace_unsynchronized::hebab37398c391bd7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f147c81bc5d - std::sys_common::backtrace::_print_fmt::h301516df68ed24f9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f147c81bc5d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f5170f4f03a12c0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f147c867fac - core::fmt::write::h5dc5601e8d9f6367
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f147c8138c8 - std::io::Write::write_fmt::h5b19302eb99d9acf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f147c81e2e7 - std::sys_common::backtrace::_print::hd81cf53a75c8ae6a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f147c81e2e7 - std::sys_common::backtrace::print::hb5aa882e87c2a0dc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f147c81e2e7 - std::panicking::default_hook::{{closure}}::had913369af61b326
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f147c81dfb0 - std::panicking::default_hook::h37b06af9ee965447
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f147c81ea39 - std::panicking::rust_panic_with_hook::hf2019958d21362cc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7f147c81e727 - std::panicking::begin_panic_handler::{{closure}}::he9c06fdd592f8785
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7f147c81c124 - std::sys_common::backtrace::__rust_end_short_backtrace::ha521b96560789310
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f147c81e439 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7f147b94ba23 - core::panicking::panic_fmt::h28f1697d4e9394b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7f147c267afe - dump_parser::postgres::get_tokens_from_query_str::h5c129d0e7d926086
  16:     0x7f147b982287 - replibyte::source::postgres::read_and_transform::{{closure}}::h38d9592830b06c69
  17:     0x7f147b97b9d6 - dump_parser::utils::list_sql_queries_from_dump_reader::h540f884dd1afeb0d
  18:     0x7f147b9dad0f - <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run::ha2213c1574b9739f
  19:     0x7f147ba97a55 - replibyte::commands::dump::run::h86af3c9d6a23f4c9
  20:     0x7f147ba59b30 - replibyte::main::h880123c1e7bd6b08
  21:     0x7f147ba8b9b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9dd32b852f85f8a3
  22:     0x7f147b9f1e89 - std::rt::lang_start::{{closure}}::h434a6ad0c3bb7757
  23:     0x7f147c81b3b4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd127f27863548251
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  24:     0x7f147c81b3b4 - std::panicking::try::do_call::h926290883a1d024e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  25:     0x7f147c81b3b4 - std::panicking::try::hc74a3d1f4a4b6e5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  26:     0x7f147c81b3b4 - std::panic::catch_unwind::h5eb7ded2df1a4d5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  27:     0x7f147c81b3b4 - std::rt::lang_start_internal::{{closure}}::h0736f9682f7c55ea
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  28:     0x7f147c81b3b4 - std::panicking::try::do_call::h2772c479b1c89ef7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  29:     0x7f147c81b3b4 - std::panicking::try::h967ebbc371287391
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  30:     0x7f147c81b3b4 - std::panic::catch_unwind::h41bcc02b28316856
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  31:     0x7f147c81b3b4 - std::rt::lang_start_internal::haf46799f55774d07
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  32:     0x7f147ba5db02 - main
```

**Comment by benny-n** [comment] 2022-05-10 11:29
Hi @fazo96 
Could you give an example of such column value that might have caused the crash so that we can reproduce this behavior?

**Comment by fazo96** [comment] 2022-05-12 13:06
Hi @benny-n, I tried narrowing down the problematic database to just one value or even column/row.

However I could only narrow it down to one table. It seems that reproducing with just the rows in the log right before the crash, or just the column that seems to contain the bad value doesn't work. So it might be a difficult bug to track down.

Can you provide an email address to which I can send the PostgreSQL database dump you can use to reproduce? It is a 2.5 MB file.

Just restore the dump and then try to run replibyte with the database you restored as the source. Replibyte will crash with the error above after running for less than a minute.

You can email me at enrico.fasoli1996 at gmail.

**Comment by fazo96** [comment] 2022-05-13 07:25
I have sent the affected dump via email. Hopefully it proves useful

**Comment by evoxmusic** [comment] 2022-05-13 18:22
Happy to take a look as well @fazo96 - my email is romaric at qovery dot com

**Comment by fazo96** [comment] 2022-05-13 18:27
@evoxmusic I forwarded you the email with the reproduction case.

Thanks for taking a swift interest in fixing the issue!

**Comment by benny-n** [comment] 2022-05-14 10:11
This was a somewhat difficult error to track down, but I think finally have a general idea of why it's happening.

First of all, the error `'TokenizerError { message: "Unterminated string literal"}` is actually a _side effect_ of a problem that occurs even earlier.

The problem comes from the function `dump_parser::utils::list_sql_queries_from_dump_reader`.

Let's take this short part of a dump for example: 
```sql
INSERT INTO public.Users(uuid, "text", name) VALUES ('a84ac0c6-2348-45c0-b86c-8d34e251a859', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu nisi tempor, viverra turpis sit amet, sodales augue. Vivamus sit amet erat urna. Morbi porta, quam nec consequat suscipit, ante diam tempus risus, et consequat erat odio sed magna. Maecenas dignissim quam nibh, nec congue magna convallis a.

Etiam augue augue, bibendum et molestie non, finibus non nulla. Etiam quis rhoncus leo, eu congue erat. Cras id magna ac dui convallis ultricies. Donec sed elit ac urna condimentum auctor. Nunc nec nulla id dui feugiat dictum sit amet nec orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.


', 'some-name');
```
Notice how in the 2nd column (text) we have `\n` re-occuring 3 times consecutively at the end of the string.
What happens is that this query gets parsed as two distinct queries(!), with everything until the 3rd `\n` being parsed as one query, and `', 'some-name');` being parsed as a different query, **EVEN THOUGH** it's a part of the 1st query.
Now, as you can see `', 'some-name');` has an odd number of single quotes, which will definitely cause some weird side effects down the line, one of them being `'TokenizerError { message: "Unterminated string literal"}` .

I've debugged `list_sql_queries_from_dump_reader` line-by-line, and I think I know why this happens: 

The 1st time is `\n` appears is okay, since we always read until `\n`
```rs
let bytes = dump_reader.read_until(b'\n', &mut line_buf_bytes);
```
The 2nd is also okay, since we check if the number of bytes in the **previous** iteration is larger than 1, and also if the empty line count is zero.
```rs
if buf_bytes.len() > 1 && count_empty_lines == 0 {
// ...
}
```
But in the 3rd consecutive `\n`, buf_bytes.len() is 1, but count_empty_lines isn't 0, and so we skip the `if` condition and we **NEVER GET TO THE CODE WHICH SAVES THE QUERY FOR THE NEXT ITERATION** :
```rs
// AFTER 3 CONSECUTIVE \n BYTES, WE DON'T GET HERE!!!
Statement::Query(sql_statement) => {
    if sql_statement.valid {
        query(sql_statement.statement);
    } else {
        // the query is not complete, so keep it for the next iteration <<< WE DON'T GET HERE: QUERY ISN'T KEPT FOR NEXT ITERATION
        buf_bytes_to_keep
            .extend_from_slice(sql_statement.statement.as_bytes());
    }
}
```
And then we reach the code which clears the buffer:
```rs
let _ = buf_bytes.clear();
buf_bytes.extend_from_slice(buf_bytes_to_keep.as_slice());
count_empty_lines += 1;
```
So the buffer gets cleared, the previous query information is lost, and `', 'some-name');` get parsed as **NEW VALID QUERY** even though it's just a part of the query that came before it, and causes unwanted side-effects in the parsing that will come later.

I think that if we manage to provide a fix for this problem, it will definitely fix the `'TokenizerError { message: "Unterminated string literal"}`  which is why this issue was opened to begin with.

So far I haven't been able to provide a workaround to prevent this error from happening, but I think we're getting a lot closer to solving this bug.
@evoxmusic Since you know this part of code the best, any insights and suggestions from you would be extremely helpful.
Let me know WDYT.

**Comment by evoxmusic** [comment] 2022-05-14 10:30
Hi @benny-n , first of all - congrats! Because you made a huge work to troubleshoot this bug. It's a hard one and I got the same issues in the past, which led me to rewrite [a lightweight SQL parser](https://github.com/Qovery/Replibyte/blob/main/dump-parser/src/utils.rs#L158) that returns a `Statement` enum.

I make some tests on my side and I come back with some insights

**Comment by evoxmusic** [comment] 2022-05-14 19:34
@benny-n are you sure about this:

>  What happens is that this query gets parsed as two distinct queries(!), with everything until the 3rd \n being parsed as one query, and ', 'some-name'); being parsed as a different query, EVEN THOUGH it's a part of the 1st query.

I've tried to reproduce it locally with the following test and it's good

```rust
    #[test]
    fn check_list_sql_statements_with_multiple_lines() {
        let s = list_statements(
            r#"INSERT INTO public.Users(uuid, "text", name) VALUES ('a84ac0c6-2348-45c0-b86c-8d34e251a859', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu nisi tempor, viverra turpis sit amet, sodales augue. Vivamus sit amet erat urna. Morbi porta, quam nec consequat suscipit, ante diam tempus risus, et consequat erat odio sed magna. Maecenas dignissim quam nibh, nec congue magna convallis a.

Etiam augue augue, bibendum et molestie non, finibus non nulla. Etiam quis rhoncus leo, eu congue erat. Cras id magna ac dui convallis ultricies. Donec sed elit ac urna condimentum auctor. Nunc nec nulla id dui feugiat dictum sit amet nec orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.


', 'some-name');
            "#,
        );
        assert_eq!(s.len(), 3);

        match s.get(0).unwrap() {
            Statement::NewLine => {
                assert!(false);
            }
            Statement::CommentLine(_) => {
                assert!(false);
            }
            Statement::Query(s) => {
                assert!(s.valid);
            }
        }
    }
```

Can you provide me with a test representing the error? (Maybe the problem does not come from `list_statements(..)` and I need to test `list_sql_queries_from_dump_reader(..)`?

**Comment by evoxmusic** [comment] 2022-05-14 20:11
I've reproduced the issue with `list_sql_queries_from_dump_reader(..)` - indeed there is a logical issue. I'm looking at how we can fix it.

**Comment by evoxmusic** [comment] 2022-05-14 21:09
@benny-n does this PR fix the issue for you? https://github.com/Qovery/Replibyte/pull/107

**Comment by benny-n** [comment] 2022-05-14 22:18
@evoxmusic 
From my end, it looks like it does!
We should verify it with the sql dumps provided by the users who encountered this error.

**Comment by evoxmusic** [comment] 2022-05-15 09:10
I confirm - it works :) I merge and release a new version 🥳 - cc @fazo96

**Closed** 2022-05-15 09:10 UTC

**Comment by fazo96** [comment] 2022-05-16 08:27
I can confirm the issue is fixed! Thank you both! @evoxmusic @benny-n
